storage: "docker-credentials"
environment:
  - IMAGE_MANIFEST=latest-arm
script:
  - source /etc/profile
  - source storage/env
  # Temporary workaround for delay on DHCP response
  - sleep 4
  # stop systemd-networkd to drop iface address from docker0
  # NOTE: this is needed until we use sabayon/builder-arm image
  - echo "[Match]" >> /etc/systemd/network/default_dhcp.network
  - echo 'Name=eth*' >> /etc/systemd/network/default_dhcp.network
  - systemctl daemon-reload
  - systemctl restart systemd-networkd
  - systemctl start docker
  - sleep 10
  - systemctl status docker
  - ip a
  - mkdir -p $HOME/.docker
  - 'echo "{\"experimental\": \"enabled\",\"auths\": { \"https://index.docker.io/v1/\": {}}}" > $HOME/.docker/config.json'
  - git clone https://github.com/mocaccinoOS/mocaccino-micro.git
  - cd mocaccino-micro/arm
  - cp ../conf . -rfv
  - docker build --no-cache --rm -t luetpm/mocaccino-micro-toolchain:${IMAGE_MANIFEST} .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker image inspect luetpm/mocaccino-micro-toolchain:${IMAGE_MANIFEST}
  - docker push luetpm/mocaccino-micro-toolchain:${IMAGE_MANIFEST}
   #- docker manifest inspect luetpm/mocaccino-micro:latest
   #- docker manifest push --purge luetpm/mocaccino-micro:latest
name: "Build ARM luetpm/mocaccino-micro-toolchian Docker image"
image: sabayon/builder-arm
type: lxd
queue: arm_lxd
