image: 'mocaccino/builder'
storage: 'sabayonarm'
script:
- sleep 3
- source /etc/profile
- source storage/env
- systemctl start docker
- mkdir -p $HOME/.docker
- 'echo "{\"experimental\": \"enabled\",\"auths\": { \"https://index.docker.io/v1/\": {}}}" > $HOME/.docker/config.json'
- git clone $REPO_URL repo && cd repo
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker build --no-cache --rm -t ${IMAGE_NAME}:${IMAGE_MANIFEST} .
- docker push ${IMAGE_NAME}:${IMAGE_MANIFEST}
- docker manifest inspect ${IMAGE_NAME}:${IMAGE_MANIFEST}
name: "Build luetpm/mocaccino-portage Docker image"
environment:
- "REPO_URL=https://github.com/mocaccinoOS/portage-tree.git"
- IMAGE_NAME=luetpm/mocaccino-portage
- IMAGE_MANIFEST=latest-amd64
type: lxd
queue: lxd
#planned: "0 0 16 * * *"
