# Author: Sabayon Dev Team
# Description: This task create files for check mirrors sync.

name: "Infra: Mirrors Sync Status"
image: sabayon/builder
tag_namespace: "mirrors-status"
artefact_path: /mirrors
directory: /infra
source: "https://github.com/Sabayon/sbi-tasks.git"
type: docker
script:
  - source /etc/profile
  - chmod a+x scripts/mirrors_checker.sh
  - scripts/mirrors_checker.sh
  - eval 'rm -rf /mirrors/build_*.log || true'
planned: "@hourly"
