# Author: Sabayon Dev Team
# Task Cleaner
name: "Maintenance"
image: 'mocaccino/builder'
storage: "geaaru"
storage_path: "confs"
source: "https://github.com/Sabayon/sbi-tasks.git"
directory: "/infra"
script:
- source /etc/profile
- sleep 1
- luet install repository/mocaccino-extra-stable
- luet install dev-util/mottainai-cli
- mkdir -p /root/.config/
- echo 'Sourcing storage file...'
- eval '. $(pwd)/confs/mcli.keys'
- echo "=================================================================="
- export MOTTAINAI_CLI_PROFILE=mocaccino
- echo "Clean old tasks:"
- scripts/tasks_cleaner.sh
- echo "=================================================================="
planned: "@daily"
environment:
- RETENTION_PERIOD=4
- LC_ALL=en_US.UTF-8
- LUET_YES=true
type: lxd
