repository:
  description: Core repo
build:
  qa_checks: 0
  emerge:
    remove:
      - app-portage/repoman
   # Install each package separately
    split_install: 1
    preserved_rebuild: 1
    default_args: --accept-properties=-interactive -t --quiet --nospinner --oneshot --complete-graph --buildpkg
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict
  target:
    - sys-apps/portage
    - sys-devel/gcc::sabayon-distro
    - sys-devel/base-gcc::sabayon-distro
    - sys-devel/libtool
    - app-arch/bzip2
    - app-arch/gzip
    - app-arch/tar
    - app-arch/xz-utils
    - app-shells/bash
    - net-misc/iputils
    - net-misc/rsync
    - net-misc/wget
    - sys-apps/busybox
    - sys-apps/coreutils
    - sys-apps/diffutils
    - sys-apps/file
    - sys-apps/gawk
    - sys-apps/grep
    - sys-apps/iproute2
    - sys-apps/kbd
    - sys-apps/less
    - sys-apps/man-pages
    - sys-apps/net-tools
    - sys-apps/sed
    - sys-apps/util-linux
    - sys-apps/which
    - sys-devel/binutils
    - sys-devel/gnuconfig
    - sys-devel/make
    - sys-fs/e2fsprogs
    - sys-process/procps
    - sys-process/psmisc
    - virtual/dev-manager
    - virtual/editor
    - virtual/libc
    - virtual/man
    - virtual/modutils
    - virtual/os-headers
    - virtual/package-manager
    - virtual/pager
    - virtual/service-manager
    - virtual/shadow
    - virtual/ssh
