#!/bin/bash

IDS=$(mottainai-cli node list | awk '{ print $4 }' | grep -v 'HOSTNAME' | xargs echo)

echo "Nodes: $IDS"
for i in $IDS;
do
	mottainai-cli task create --yaml infra/clean.yaml --to $i
done
