#!/bin/bash
set -ex

DOCKER_IMAGES="${DOCKER_IMAGES:-0 0 16 * * *}"

# Docker images
mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/Sabayon/sbi-tasks.git \
                            -s Arch=amd64 \
                            -s Recurring="$DOCKER_IMAGES" \
                            -s Image=sabayon/ci \
                            -s Directory=bots/ \
                            -o bots/docker-image.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/MottainaiCI/mottainai-server \
                            -s Arch=amd64 \
                            -s Image=mottainaici/server \
                            -s Directory=/ \
                            -s Recurring="$DOCKER_IMAGES" \
                            -o image_build/docker/mottainai/server-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/MottainaiCI/mottainai-agent \
                            -s Arch=amd64 \
                            -s Image=mottainaici/agent \
                            -s Recurring="$DOCKER_IMAGES" \
                            -s Directory=/ \
                            -o image_build/docker/mottainai/agent-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/MottainaiCI/mottainai-cli \
                            -s Arch=amd64 \
                            -s Image=mottainaici/cli \
                            -s Directory=/ \
                            -s Recurring="$DOCKER_IMAGES" \
                            -o image_build/docker/mottainai/cli-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/Sabayon/docker-spinbase-amd64 \
                            -s Arch=amd64 \
                            -s Squashed=true \
                            -s Image=sabayon/spinbase \
                            -s Recurring="0 0 20 * * *" \
                            -s Directory=/ \
                            -o image_build/docker/spinbase-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/Sabayon/docker-base-amd64 \
                            -s Arch=amd64 \
                            -s Squashed=true \
                            -s Recurring="$DOCKER_IMAGES" \
                            -s Image=sabayon/base \
                            -s Directory=/ \
                            -o image_build/docker/base-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/Sabayon/docker-isobuilder-amd64 \
                            -s Arch=amd64 \
                            -s Recurring="$DOCKER_IMAGES" \
                            -s Image=sabayon/isobuilder \
                            -s Directory=/ \
                            -o image_build/docker/isobuilder-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/Sabayon/docker-builder-amd64 \
                            -s Arch=amd64 \
                            -s Squashed=true \
                            -s Recurring="$DOCKER_IMAGES" \
                            -s Image=sabayon/builder \
                            -s Directory=/ \
                            -o image_build/docker/builder-amd64.yaml

mottainai-cli task compile image_build/docker/multiarch.tmpl \
                            -s SourceRepo=https://github.com/Sabayon/packer-templates \
                            -s Arch=amd64 \
                            -s Recurring="@monthly" \
                            -s Image=sabayon/packer \
                            -s Directory=/ \
                            -o image_build/docker/packer-amd64.yaml

# SCR 

mottainai-cli task compile scr/repo.tmpl \
                            -s SCRRepo=mudler \
                            -s Storage=3224462066628783553 \
                            -o scr/mudler.yaml

# Bots
for i in "mottainai-cli" "mottainai-agent" "replicant"
do
    mottainai-cli task compile bots/mottainai/vendor-branch-sync.tmpl \
                                -s Component="$i" \
                                -o bots/mottainai/sync-develop-"$i".yaml

    mottainai-cli task compile bots/mottainai/merge-master.tmpl \
                                -s Component="$i" \
                                -o bots/mottainai/merge-master-"$i".yaml
done

mottainai-cli task compile bots/mottainai/merge-master.tmpl \
                            -s Component=mottainai-server \
                            -o bots/mottainai/merge-master-mottainai-server.yaml


## Auto Bump bots
for i in "sabayon-distro" "for-gentoo"
do
mottainai-cli task compile bots/detect-obsoletes/detect-obsoletes.tmpl \
                            -s OverlayName=$i \
                            -s Recurring= \
                            -s UpstreamOrg=Sabayon \
                            -o bots/detect-obsoletes/detect-obsoletes-amd64-$i.yaml

mottainai-cli task compile bots/auto-bump/auto-bumper.tmpl \
                            -s OverlayName=$i \
                            -s Recurring=@weekly \
                            -s UpstreamOrg=Sabayon \
                            -o bots/auto-bump/auto-bump-$i.yaml
done