name: "ARM - Build docker image luetpm/luet"
storage: "docker-credentials"
script:
  - source /etc/profile
  - source storage/env
  # Temporary workaround for delay on DHCP response
  - sleep 4
  # stop systemd-networkd to drop iface address from docker0
  # NOTE: this is needed until we use sabayon/builder-arm image
  - echo "[Match]" >> /etc/systemd/network/default_dhcp.network
  - echo 'Name=eth*' >> /etc/systemd/network/default_dhcp.network
  - systemctl daemon-reload
  - systemctl restart systemd-networkd
  - systemctl start docker
  - sleep 10
  - systemctl status docker
  - ip a
  - mkdir -p $HOME/.docker
  - 'echo "{\"experimental\": \"enabled\",\"auths\": { \"https://index.docker.io/v1/\": {}}}" > $HOME/.docker/config.json'
  - git clone https://github.com/mudler/luet && cd luet
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker ps
  - docker build --no-cache --rm -t luetpm/luet:latest .
  - docker image inspect luetpm/luet:latest
  - docker push luetpm/luet:latest
environment:
  - BRANCH=master
  - SHELL=/bin/bash
  - ARCH=armv7
image: sabayon/builder-arm
type: lxd
directory: /
queue: arm_lxd
