source: 'https://github.com/Sabayon/packer-templates'
directory: '/'
image: 'sabayon/ci'
storage: '9317096982217158'
script:
   - source storage/env
   - mkdir -p $HOME/.docker
   - 'echo "{\"experimental\": \"enabled\",\"auths\": { \"https://index.docker.io/v1/\": {}}}" > $HOME/.docker/config.json'
   - docker build --no-cache --rm -t sabayon/packer-amd64:latest .

   - docker login -u $DOCKER_USER -p $DOCKER_PASS
   - docker push sabayon/packer-amd64:latest
   - docker manifest create --amend sabayon/packer:latest sabayon/packer-amd64:latest
   - docker manifest annotate sabayon/packer:latest sabayon/packer-amd64:latest --arch amd64 --os linux
   - docker manifest inspect sabayon/packer:latest
   - docker manifest push --purge sabayon/packer:latest
type: docker
name: "Build sabayon/packer Docker image"

planned: "@monthly"
