artefact_path: wiki
directory: /infra/wiki
environment:
  - ETP_NONINTERACTIVE=1
  - "ACCEPT_LICENSE=*"
  - REPOSITORY_NAME=wiki-tmp
  - LC_ALL=en_US.UTF-8
  - SKIP_COMMIT=1
  - SKIP_PULL=1
image: sabayon/builder-amd64
script:
  - wget https://raw.githubusercontent.com/Sabayon/sabayon-sark/master/sark-functions.sh -O /sbin/sark-functions.sh
  - chmod 755 /sbin/sark-functions.sh
  - cp -rfv /sbin/sark-functions.sh /etc/sark-functions
  - chmod 755 /etc/sark-functions
  - wget https://raw.githubusercontent.com/Sabayon/devkit/master/builder -O /usr/sbin/builder
  - wget https://raw.githubusercontent.com/Sabayon/sabayon-sark/master/sark-localbuild -O ./sark-localbuild
  - chmod a+x /usr/sbin/builder
  - chmod a+x ./sark-localbuild
  - equo up && equo upgrade
  - eval "export WIKI_DIR=$(pwd)/wiki"
  - SAB_BUILDFILE=build.yaml ./sark-localbuild
  - git clone https://github.com/Sabayon/wiki-next.git
  - cd wiki-next
  - mkdocs build --verbose --clean --strict
  - cp -rvf site/* ${WIKI_DIR}
source: https://github.com/Sabayon/sbi-tasks
tag_namespace: wiki-test
type: docker
name: "Test Wiki-Next"
