artefact_path: ../wiki
directory: /
storage: "7287247578967654972"
storage_path: ../storage
environment:
  - ETP_NONINTERACTIVE=1
  - "ACCEPT_LICENSE=*"
  - REPOSITORY_NAME=wiki-tmp
  - LC_ALL=en_US.UTF-8
  - SKIP_COMMIT=1
  - SKIP_PULL=1
  - GIT_AUTHOR_NAME=MarvinHatesOceans
  - GIT_AUTHOR_EMAIL=github-bots@sabayon.com
  - GIT_COMMITTER_NAME=MarvinHatesOceans
  - GIT_COMMITTER_EMAIL=github-bots@sabayon.com
image: sabayon/builder-amd64
script:
  - equo up
  - equo install enman
  - enman add https://downloads.svc.sabayon.org/namespace/geaaru/geaaru
  - equo update geaaru
  - equo upgrade
  - equo install dev-python/mkdocs-material dev-python/mkdocs-cinder dev-python/pymdown-extensions www-servers/tornado-5.1 hub
  - echo "====================== CONFIGURE SSH ====================="
  # Setup deps and ssh/GH access
  - eval "rm -rfv /root/.ssh || true"
  - cp -rvf ../storage /root/.ssh
  - mkdir -p ~/.config/
  - eval "rm -rfv /root/.config/hub || true"
  - cp -rvf ../storage/hub /root/.config/hub
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa.pub
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo "====================== SSH READY ====================="
  - eval "export WIKI_DIR=$(pwd)/../wiki"
  - mkdocs build --verbose --clean --strict
  - cp -rvf site/* ${WIKI_DIR}
  - git checkout gh-pages
  - rm -rf ./*
  - cp -rvf ${WIKI_DIR}/* .
  - echo "====================== STATUS ====================="
  - git status .
  - echo "====================== ADD ====================="
  - git add .
  - echo "====================== COMMIT ====================="
  - git commit -m "Update wiki-next gh-pages"
  - git status .
  - echo "====================== PUSH ====================="
  - git remote set-url origin git@github.com:Sabayon/wiki-next.git
  - git push
  - echo "====================== ALL DONE ====================="
source: https://github.com/Sabayon/wiki-next.git
type: docker
name: "Wiki-next: Update gh-pages"
