artefact_path: ../www
directory: /
storage: "7287247578967654972"
storage_path: ../storage
environment:
  - ETP_NONINTERACTIVE=1
  - "ACCEPT_LICENSE=*"
  - LC_ALL=en_US.UTF-8
  - SKIP_COMMIT=1
  - SKIP_PULL=1
  - GIT_AUTHOR_NAME=MarvinHatesOceans
  - GIT_AUTHOR_EMAIL=github-bots@sabayon.com
  - GIT_COMMITTER_NAME=MarvinHatesOceans
  - GIT_COMMITTER_EMAIL=github-bots@sabayon.com
  - GIT_WWW_BRANCH=master
  - HUGO_THEME=https://github.com/Sabayon/sabayon-website-next-theme
image: sabayon/base-amd64
script:
  - equo up
  - equo upgrade
  - equo install hub dev-lang/go
  - echo "====================== CONFIGURE SSH ====================="
  # Setup deps and ssh/GH access
  - eval "rm -rfv /root/.ssh || true"
  - ln -s $(pwd)/../storage /root/.ssh
  - mkdir -p ~/.config/
  - eval "rm -rfv /root/.config/hub || true"
  - ln -s $(pwd)/../storage/hub /root/.config/hub
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa.pub
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo "====================== SSH READY ====================="
  - eval "export WWW_DIR=$(pwd)/../www/"
  - git checkout ${GIT_WWW_BRANCH}
  - sed -i -e 's:baseurl.*:baseurl = "https\://dispatcher.sabayon.org/sbi/namespace/website-next/":g' config.toml
  - make build
  - cp -rvf public/* ${WWW_DIR}
  - echo "====================== ALL DONE ====================="
source: https://github.com/Sabayon/sabayon-website-next.git
type: docker
# Publish website under mottainai namespace
# to validate output.
tag_namespace: "website-next"
name: "sabayon-website-next: Test site"
